# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170321_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='data',
        ),
    ]
