# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_movie_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='undescribed', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='unnamed', max_length=200),
        ),
    ]
