# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170324_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='movie',
            name='img_url',
            field=models.TextField(default='none'),
        ),
    ]
