# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170413_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='apple_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='movie',
            name='apple_url',
            field=models.TextField(default='none'),
        ),
    ]
