# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170425_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='netflix_url',
            field=models.TextField(default='none'),
        ),
    ]
